### ISSUE TITLE
Uninitialized Analytics::Engine::AccountServices

### ISSUE THREAD

**Issue by bk322** [instructure/analytics#4]
Hi devs,
I check out latest stable Analytics plugin and on `db:migrate` I got:
```
/var/canvas: RAILS_ENV=production rake db:migrate --trace
/var/canvas/vendor/bundle/ruby/1.9.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require': iconv will be deprecated in the future, use String#encode instead.
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NameError: uninitialized constant Analytics::Engine::AccountServices
/var/canvas/gems/plugins/analytics/lib/analytics/engine.rb:23:in `block in <class:Engine>'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-b344986bc3d9/railties/lib/rails/initializable.rb:30:in `instance_exec'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-b344986bc3d9/railties/lib/rails/initializable.rb:30:in `run'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-b344986bc3d9/railties/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-b344986bc3d9/railties/lib/rails/initializable.rb:54:in `each'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-b344986bc3d9/railties/lib/rails/initializable.rb:54:in `run_initializers'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-b344986bc3d9/railties/lib/rails/application.rb:136:in `initialize!'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-b344986bc3d9/railties/lib/rails/railtie/configurable.rb:30:in `method_missing'
/var/canvas/config/environment.rb:23:in `<top (required)>'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-b344986bc3d9/railties/lib/rails/application.rb:103:in `require_environment!'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-b344986bc3d9/railties/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => db:migrate => environment
```
Running `cassandra` and its migrations went fine. 
I'm running stable Canvas from April 2015.
Any help will be greately appreciated.

**Comment by ccutrer** [comment]
Analytics stable branches must be matched with the same stable branch from canvas-lms. You need to either update your canvas-lmd, or use an older analytics.

**Comment by knollies** [comment]
I'm running stable canvas and analytics stable version  from Dec 2015. I get the same error.

**Comment by arunkumargit** [comment]
I'm running canvas and analytics stable version from Dec 2015. I get the same error. Is there any solution ?
